### PR TITLE
Constant branch name

### PR DESCRIPTION
**Pull request by dword-design**
I think it makes more sense to use a constant branch + PR and update it. This way we do not have multiple PRs in case the metadata change more often.

We need to have these PRs fixed for this:
* https://github.com/Jaid/commit-from-action/pull/26
* https://github.com/Jaid/commit-from-action/pull/25

### CODE REVIEW

**Comment by Jaid** [comment]
I am not quite sure if this change could lead to unexpected consequences, but I'm gladly willing to try.

`commitManager.options.branch` is now available in [commit-from-action v2](https://github.com/Jaid/commit-from-action/releases/tag/v2.0.0).

**Comment by Jaid** [comment]
I'll add the user's choice between a constant branch name and a randomly generated branch name later this day.

**Comment by Jaid** [comment]
New change based on this pull request:

- [Added input “branch” (“action-sync-node-meta” by default)](https://github.com/Jaid/action-sync-node-meta/commit/4ac0cb36afcde6c3f9b5ebd2b4293c1418828a96)

Constant branch name is the new default now.

```yaml
- name: Jaid/action-sync-node-meta
  uses: jaid/action-sync-node-meta@v2.0.0
  with:
    githubToken: ${{ secrets.GITHUB_TOKEN }}
    branch: action-sync-node-meta
```

Random addition is optional.

```yaml
- name: Jaid/action-sync-node-meta
  uses: jaid/action-sync-node-meta@v2.0.0
  with:
    githubToken: ${{ secrets.GITHUB_TOKEN }}
    branch: action-sync-node-meta_{random}
```

**Comment by dword-design** [comment]
@Jaid even better

**Pull request closed without merging**
